import { Download, TrendingUp, Users, BookOpen, Activity } from 'lucide-react';

function AdminReports() {
  const reportTypes = [
    { id: 1, name: 'Student Performance Report', description: 'Detailed analysis of student grades and progress', icon: TrendingUp, color: 'orange' },
    { id: 2, name: 'Enrollment Report', description: 'Course enrollment statistics and trends', icon: Users, color: 'blue' },
    { id: 3, name: 'Course Analytics', description: 'Course completion rates and feedback', icon: BookOpen, color: 'green' },
    { id: 4, name: 'System Activity Report', description: 'Platform usage and activity metrics', icon: Activity, color: 'purple' }
  ];

  const recentReports = [
    { id: 1, name: 'Fall 2024 Enrollment Report', generatedAt: '2024-05-10', generatedBy: 'Admin Pham D', size: '2.4 MB' },
    { id: 2, name: 'Student Performance Q1 2024', generatedAt: '2024-04-15', generatedBy: 'Admin Nguyen A', size: '3.1 MB' },
    { id: 3, name: 'Course Completion Analysis', generatedAt: '2024-04-01', generatedBy: 'Admin Tran B', size: '1.8 MB' }
  ];

  const getIconBgColor = (color: string) => {
    const colors: { [key: string]: string } = {
      orange: 'bg-[#FFF5ED] text-[#F37022]',
      blue: 'bg-blue-100 text-blue-600',
      green: 'bg-green-100 text-green-600',
      purple: 'bg-purple-100 text-purple-600'
    };
    return colors[color] || 'bg-gray-100 text-gray-600';
  };

  return (
    <div className="p-4 md:p-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:justify-between sm:items-start gap-4 mb-6 md:mb-8">
        <div>
          <h1 className="text-2xl md:text-3xl font-bold text-[#0A1B3C]">Reports</h1>
        </div>
        <button className="flex items-center justify-center gap-2 px-4 py-2.5 bg-[#F37022] text-white rounded-lg text-sm md:text-base font-semibold">
          <Download className="w-4 h-4" />
          <span className="hidden sm:inline">Generate Custom Report</span>
          <span className="sm:hidden">Generate Report</span>
        </button>
      </div>

      {/* Report Types */}
      <div className="bg-white rounded-xl border border-gray-200 p-4 md:p-6 mb-4 md:mb-6">
        <h2 className="text-lg md:text-xl font-bold text-[#0A1B3C] mb-4 md:mb-6">Report Types</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {reportTypes.map(report => {
            const Icon = report.icon;
            return (
              <div key={report.id} className="bg-white border border-gray-200 rounded-lg p-6 hover:shadow-lg transition-shadow cursor-pointer">
                <div className="flex gap-4 mb-4">
                  <div className={`w-14 h-14 rounded-lg flex items-center justify-center ${getIconBgColor(report.color)}`}>
                    <Icon className="w-6 h-6" />
                  </div>
                  <div className="flex-1">
                    <h3 className="text-base font-semibold text-[#0A1B3C] mb-1">{report.name}</h3>
                    <p className="text-sm text-gray-600">{report.description}</p>
                  </div>
                </div>
                <button className="w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-[#F37022] text-white rounded-lg font-semibold">
                  <Download className="w-4 h-4" />
                  Generate Report
                </button>
              </div>
            );
          })}
        </div>
      </div>

      {/* Recent Reports */}
      <div className="bg-white rounded-xl border border-gray-200 p-4 md:p-6 mb-4 md:mb-6">
        <div className="flex justify-between items-center mb-4 md:mb-6">
          <h2 className="text-lg md:text-xl font-bold text-[#0A1B3C]">Recent Reports</h2>
          <a href="#" className="text-[#F37022] text-sm font-medium hover:underline">View All</a>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="border-b-2 border-gray-200">
                <th className="p-3 text-left text-sm font-semibold text-gray-700">Report Name</th>
                <th className="p-3 text-center text-sm font-semibold text-gray-700">Generated Date</th>
                <th className="p-3 text-left text-sm font-semibold text-gray-700">Generated By</th>
                <th className="p-3 text-center text-sm font-semibold text-gray-700">File Size</th>
                <th className="p-3 text-center text-sm font-semibold text-gray-700">Action</th>
              </tr>
            </thead>
            <tbody>
              {recentReports.map(report => (
                <tr key={report.id} className="border-b border-gray-100">
                  <td className="p-4 text-sm font-medium text-[#0A1B3C]">{report.name}</td>
                  <td className="p-4 text-center text-sm text-gray-600">
                    {new Date(report.generatedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                  </td>
                  <td className="p-4 text-sm text-gray-600">{report.generatedBy}</td>
                  <td className="p-4 text-center text-sm text-gray-600">{report.size}</td>
                  <td className="p-4 text-center">
                    <button className="inline-flex items-center gap-1.5 px-4 py-1.5 bg-[#F37022] text-white rounded-lg text-sm font-semibold">
                      <Download className="w-3.5 h-3.5" />
                      Download
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Quick Stats */}
      <div className="bg-white rounded-xl border border-gray-200 p-4 md:p-6">
        <h2 className="text-lg md:text-xl font-bold text-[#0A1B3C] mb-4 md:mb-6">Quick Stats</h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3 md:gap-6">
          <div className="bg-white border border-gray-200 rounded-lg p-5">
            <div className="flex items-start justify-between mb-4">
              <div>
                <div className="text-2xl font-bold text-[#0A1B3C]">2,847</div>
                <div className="text-sm text-gray-600">Total Users</div>
              </div>
              <div className="p-3 bg-[#FFF5ED] rounded-lg">
                <Users className="w-5 h-5 text-[#F37022]" />
              </div>
            </div>
            <div className="text-sm text-green-600 font-medium">+137 this month</div>
          </div>
          <div className="bg-white border border-gray-200 rounded-lg p-5">
            <div className="flex items-start justify-between mb-4">
              <div>
                <div className="text-2xl font-bold text-[#0A1B3C]">156</div>
                <div className="text-sm text-gray-600">Active Courses</div>
              </div>
              <div className="p-3 bg-blue-100 rounded-lg">
                <BookOpen className="w-5 h-5 text-blue-600" />
              </div>
            </div>
            <div className="text-sm text-green-600 font-medium">+12 this semester</div>
          </div>
          <div className="bg-white border border-gray-200 rounded-lg p-5">
            <div className="flex items-start justify-between mb-4">
              <div>
                <div className="text-2xl font-bold text-[#0A1B3C]">89%</div>
                <div className="text-sm text-gray-600">Completion Rate</div>
              </div>
              <div className="p-3 bg-green-100 rounded-lg">
                <TrendingUp className="w-5 h-5 text-green-600" />
              </div>
            </div>
            <div className="text-sm text-green-600 font-medium">+4% from last term</div>
          </div>
          <div className="bg-white border border-gray-200 rounded-lg p-5">
            <div className="flex items-start justify-between mb-4">
              <div>
                <div className="text-2xl font-bold text-[#0A1B3C]">99.9%</div>
                <div className="text-sm text-gray-600">System Uptime</div>
              </div>
              <div className="p-3 bg-purple-100 rounded-lg">
                <Activity className="w-5 h-5 text-purple-600" />
              </div>
            </div>
            <div className="text-sm text-green-600 font-medium">Last 30 days</div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default AdminReports;
