name: Deploy Frontend to ECR and ECS

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.registry }}
          ECR_REPOSITORY: fuec/dev-fe
          IMAGE_TAG: latest
          VITE_API_URL: https://fuec.site/api/v1
          VITE_GOOGLE_CLIENT_ID: 843091633958-ehu83jknrt3paisrelcpp2v95aj3a4ae.apps.googleusercontent.com
        run: |
          docker build \
            --build-arg VITE_API_URL=$VITE_API_URL \
            --build-arg VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Notify Jenkins to Deploy
        run: |
          # Gọi webhook để báo cho Jenkins biết đã build xong
          # Bạn cần cài đặt JENKINS_USER và JENKINS_TOKEN trong GitHub Secrets
          # Đảm bảo server Jenkins của bạn đang ONLINE (Running)
          curl -I -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} "https://jenkins.fuec.site/job/FUEC-FE-Deploy/build"
